# Generated by Django 5.0.4 on 2024-05-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_category_note_checked_alter_note_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
    ]
